# Generated by Django 4.1.2 on 2022-10-13 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=511)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='WOWPDF/icons')),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ToolFile',
            },
        ),
        migrations.CreateModel(
            name='WowFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='WOWPDF/files/%Y/%m')),
                ('file2', models.FileField(blank=True, null=True, upload_to='WOWPDF/files/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_compressed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'WowFiles',
            },
        ),
    ]
